---
abstract: 'IRC network indexing system'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRC-Indexer
provides:
  IRC::Indexer:
    file: lib/IRC/Indexer.pm
    version: 0.01_01
  IRC::Indexer::Conf:
    file: lib/IRC/Indexer/Conf.pm
    version: 0
  IRC::Indexer::Info::Network:
    file: lib/IRC/Indexer/Info/Network.pm
    version: 0
  IRC::Indexer::Info::Server:
    file: lib/IRC/Indexer/Info/Server.pm
    version: 0
  IRC::Indexer::Logger:
    file: lib/IRC/Indexer/Logger.pm
    version: 0
  IRC::Indexer::Output:
    file: lib/IRC/Indexer/Output.pm
    version: 0
  IRC::Indexer::Output::Dumper:
    file: lib/IRC/Indexer/Output/Dumper.pm
    version: 0
  IRC::Indexer::Output::JSON:
    file: lib/IRC/Indexer/Output/JSON.pm
    version: 0
  IRC::Indexer::Output::YAML:
    file: lib/IRC/Indexer/Output/YAML.pm
    version: 0
  IRC::Indexer::Trawl::Bot:
    file: lib/IRC/Indexer/Trawl/Bot.pm
    version: 0
  IRC::Indexer::Trawl::Multi:
    file: lib/IRC/Indexer/Trawl/Multi.pm
    version: 0
requires:
  Data::Dumper: 0
  Getopt::Long: 0
  IRC::Utils: 0
  JSON::XS: 0
  Log::Handler: 0
  POE: 1.311
  POE::Component::IRC::State: 6.74
  POEx::HTTP::Server: 0
  POSIX: 0
  Scalar::Util: 0
  Storable: 0
  URI: 0
  YAML::XS: 0
  perl: v5.12.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
