=pod

=head1 NAME

CommandSpec - IRC::Indexer command protocol

=head2 Clients

=head3 From Server

Delivered from server via client's C<ZMQ_DEALER> socket.

=head4 PONG

A client that sent L</PING> should accept a reply containing C<PONG> as
indication that the server is responsive.

=head2 Server

=head3 From Clients

Delivered to server's C<ZMQ_ROUTER> by C<ZMQ_DEALER> clients.

=head4 PING

A C<PING> should cause a L</PONG> to be sent to the originating client.

=head4 BATCH

  BATCH <JSON>

A batch of servers to be indexed.

C<< <JSON> >> should be a JSON-encoded HASH in the format of (perl):

  +{ $SERVER_NAME => +{ %OPTS }, ... }

Currently known valid C<%OPTS> keys are:

=over

=item port

=back

=head3 From Peers

Delivered to server's C<ZMQ_ROUTER> by C<ZMQ_ROUTER> peers.

=head4 STATE

Request immediate publication of peer L</STATUS>.

=head2 State

Published by servers via C<ZMQ_PUB> for use by peer servers.

=head3 STATUS

  STATUS <total workers> <busy workers>

=head2 Worker

FIXME

=cut
